// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAkke-euKHBw2Zi4G2ltfmXC_2tzbGfI0',
    appId: '1:692686355338:web:9ea6b3810905252112e673',
    messagingSenderId: '692686355338',
    projectId: 'genius-9c753',
    authDomain: 'genius-9c753.firebaseapp.com',
    storageBucket: 'genius-9c753.appspot.com',
    measurementId: 'G-2S09L87T7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3Sj7OQ6dromqL94IJCardBHbxmfbZNE',
    appId: '1:692686355338:android:e0ec6a279852120612e673',
    messagingSenderId: '692686355338',
    projectId: 'genius-9c753',
    storageBucket: 'genius-9c753.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09111hdEAspvWzB2ZdiIKZqcKC5bhNOI',
    appId: '1:692686355338:ios:98e6c1374da63a7212e673',
    messagingSenderId: '692686355338',
    projectId: 'genius-9c753',
    storageBucket: 'genius-9c753.appspot.com',
    iosBundleId: 'com.example.genius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09111hdEAspvWzB2ZdiIKZqcKC5bhNOI',
    appId: '1:692686355338:ios:b207a475849e7afa12e673',
    messagingSenderId: '692686355338',
    projectId: 'genius-9c753',
    storageBucket: 'genius-9c753.appspot.com',
    iosBundleId: 'com.example.genius.RunnerTests',
  );
}
